# yaml-language-server: $schema=https://json.schemastore.org/lefthook.json

pre-commit:
  commands:
    pre-commit:
      run: devbox run -- task pre-commit

commit-msg:
  commands:
    conform:
      run: devbox run -- conform enforce --commit-msg-file {1}
