version: "3"

set: [errexit, nounset, pipefail]
shopt: [globstar]

includes:
  dev: ./.taskfiles/dev/Taskfile.yaml
  fmt: ./.taskfiles/fmt/Taskfile.yaml
  gh: ./.taskfiles/gh/Taskfile.yaml
  git: ./.taskfiles/git/Taskfile.yaml
  go: ./.taskfiles/go/Taskfile.yaml

tasks:
  default:
    cmd: task -l

  format:
    desc: Runs all format targets
    deps: [go:format, fmt:format]

  lint:
    desc: Runs all lint targets
    deps: [go:lint, gh:lint, fmt:lint]

  docs:
    desc: Runs all docs targets
    deps: [go:docs]

  test:
    desc: Runs all test targets
    deps: [go:test]

  pre-commit:
    desc: Runs all pre-commit targets
    cmds:
      - task: format
      - task: lint
      - task: test

  build:
    desc: Runs all build targets
    deps: [go:build]

  install:
    desc: Runs all install targets
    deps: [dev:install, git:hooks:install]

  shell:
    desc: Launches a shell in the devcontainer
    aliases: [sh]
    interactive: true
    cmd:
      task: dev:shell

  claude:
    desc: Launches a Claude Code session in the devcontainer
    aliases: [cc]
    interactive: true
    cmd:
      task: dev:claude

  clean:
    desc: Removes build artifacts and caches
    cmds:
      - rm -rf dist/ .test/ .task/ .tmp/
