package jsonschema_test

import (
	"bytes"
	"context"
	"encoding/json/jsontext"
	"encoding/json/v2"
	"maps"
	"reflect"
	"slices"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"

	"go.jacobcolvin.com/x/jsonschema"
	"go.jacobcolvin.com/x/jsonschema/internal/fuzzfill"
	"go.jacobcolvin.com/x/jsonschema/internal/fuzzshape"
	"go.jacobcolvin.com/x/jsonschema/internal/reflectkind"
)

// Rig 2 -- reflection vs encoding/json, over a synthesized type shape. Rig 1
// asserts the same property over a hand-written roster, so it only catches
// drift in shapes someone already thought to write down. This rig fuzzes the
// type shape as well as the value:
//
//	Compile(Generate(fuzzshape.Type(shape))).ValidateJSON(json.Marshal(v)) == nil
//
// The callback takes two blobs so shape and value entropy evolve
// independently; the fuzzing engine mutates each on its own. That arity means
// rig 1's addReflectSeeds cannot be reused, since f.Add panics unless its
// arity matches the callback's.
//
// FuzzShapeRejectsNearMiss is the complement: a schema that accepts everything
// would satisfy the accept rigs trivially, so it asserts that instances just
// outside the type's marshaled shape are refused.

// Three causes would make a synthesized shape report a divergence the package
// is not guilty of. Each has a reason constant carried as the message of a
// guard that pins the cause down, so an exclusion cannot quietly stop being
// true. The two below are the rig's own: one explains a variant the rig
// deliberately does not have, the other why a coverage class stays in rig 1's
// roster. The third constrains fuzzshape's pools and lives with the guard over
// them, as reasonUnmodeledMarshaler in internal/fuzzshape.

// reasonStructOfPromotion is why the promoted-marshaler and embedded-generic
// classes stay in rig 1's static roster, where the compiler builds the
// promotion wrappers for real. It describes a limitation of runtime type
// construction rather than package behavior, and so is deliberately absent from
// doc.go and README.md: documenting it publicly would describe the package as
// behaving in a way it does not.
const reasonStructOfPromotion = "reflect.StructOf cannot reproduce method promotion: a synthesized embed's promoted method reports the embedded type's real source file rather than the <autogenerated> marker reflectkind.HasDirectMethod keys on, so it is misclassified as direct. It also cannot name a generic instantiation, since Wrap[string] is not a valid Go field name"

// reasonNullableOff is why the accept rigs have no WithNullable(false) variant.
const reasonNullableOff = "WithNullable(false) deliberately drops the null branch, so a nil pointer marshaling to null is correctly rejected and the accept property does not hold"

// reasonFallbackAdmitsExtras is why FuzzShapeRejectsNearMiss skips its
// extra-property leg when the drawn shape carries a winning embedded
// fallback. TestShapeFallbackNearMissTeeth restores the leg's teeth
// deterministically.
const reasonFallbackAdmitsExtras = "an embedded fallback's value schema admits unknown members by design, so an injected sentinel property is not a near miss; the schema still constrains each member's value"

// nearMissSentinel is the property name FuzzShapeRejectsNearMiss injects. No
// fuzzshape tag pool entry can produce it, so its absence from a marshaled
// instance is guaranteed; the rig asserts that anyway rather than trusting it.
const nearMissSentinel = "__fuzzshape_sentinel__"

// TestShapeNullableOffRejectsNull pins down reasonNullableOff and keeps the
// accept rigs' omission of that variant honest: were the option ever to admit
// null, this fails and the variant can be added.
func TestShapeNullableOffRejectsNull(t *testing.T) {
	t.Parallel()

	ctx := t.Context()

	schema, err := jsonschema.GenerateFor[plainChild](ctx, jsonschema.WithNullable(false))
	require.NoError(t, err)

	validator, err := jsonschema.Compile(ctx, schema)
	require.NoError(t, err)

	instance, err := json.Marshal(plainChild{})
	require.NoError(t, err)
	require.Contains(t, string(instance), `"deep":null`, "the nil pointer must marshal to null")

	require.Error(t, validator.ValidateJSON(ctx, instance), reasonNullableOff)
}

// TestShapeStructOfCannotReproducePromotion pins down reasonStructOfPromotion.
// A statically declared embed's promoted method carries the <autogenerated>
// source location reflectkind keys on; the same embed built by reflect.StructOf
// carries the embedded type's real source file and so reads as directly
// declared. That inversion is why promoted-marshaler coverage stays in rig 1's
// roster. Were Go ever to make StructOf reproduce promotion, this fails and the
// coverage could move.
func TestShapeStructOfCannotReproducePromotion(t *testing.T) {
	t.Parallel()

	declared := reflect.TypeFor[promotedTextMarshaler]()
	require.True(t, reflectkind.ImplementsAnyTextMarshaler(declared) &&
		!reflectkind.HasDirectMethod(declared, "MarshalText"),
		"a declared embed must read as promoted")

	synthesized := reflect.StructOf([]reflect.StructField{
		{Name: "Celsius", Type: reflect.TypeFor[Celsius](), Anonymous: true},
	})
	require.True(t, reflectkind.ImplementsAnyTextMarshaler(synthesized) &&
		reflectkind.HasDirectMethod(synthesized, "MarshalText"), reasonStructOfPromotion)

	// The reason's other half: an embedded generic instantiation cannot be named
	// at all, since a field name must be an identifier.
	require.Panics(t, func() {
		reflect.StructOf([]reflect.StructField{
			{Name: "Wrap[int]", Type: reflect.TypeFor[Wrap[int]](), Anonymous: true},
		})
	}, reasonStructOfPromotion)
}

func FuzzShapeAccepts(f *testing.F) {
	fuzzShapeAccepts(f, nil, nil)
}

// FuzzShapeAcceptsDraft7 targets Draft-07, whose $ref and definitions handling
// differs enough from Draft 2020-12 to reach different generation paths.
func FuzzShapeAcceptsDraft7(f *testing.F) {
	fuzzShapeAccepts(f, []jsonschema.GenerateOption{jsonschema.WithDraft(jsonschema.Draft7)}, nil)
}

// FuzzShapeAcceptsOpenObjects drops additionalProperties: false. The property
// still has teeth: an open object only stops rejecting unknown keys, and every
// declared property's own schema still has to admit what the field marshals to.
func FuzzShapeAcceptsOpenObjects(f *testing.F) {
	fuzzShapeAccepts(f, []jsonschema.GenerateOption{jsonschema.WithAdditionalProperties(true)}, nil)
}

// FuzzShapeAcceptsNoDefs inlines every named type instead of extracting it to
// $defs, so the pooled named structs are reflected at each use site rather than
// once behind a $ref.
func FuzzShapeAcceptsNoDefs(f *testing.F) {
	fuzzShapeAccepts(f, []jsonschema.GenerateOption{jsonschema.WithDefinitions(false)}, nil)
}

// FuzzShapeAcceptsWithFormats turns on format assertion, so the pool's
// time.Time fields must satisfy the date-time format validator, the same RFC
// 3339 round-trip rig 1 covers with timeWrapper.
func FuzzShapeAcceptsWithFormats(f *testing.F) {
	fuzzShapeAccepts(f, nil, []jsonschema.ValidateOption{jsonschema.WithFormats(true)})
}

// FuzzShapeAcceptsNilContainersNull pairs WithJSONOptions(FormatNil*AsNull)
// generation with the same marshal options and the nil-container fill draw;
// without that draw the default fill never produces a nil slice or map and
// the target would assert nothing new.
func FuzzShapeAcceptsNilContainersNull(f *testing.F) {
	opts := []json.Options{json.FormatNilSliceAsNull(true), json.FormatNilMapAsNull(true)}
	fuzzShapeAcceptsOpts(f,
		[]jsonschema.GenerateOption{jsonschema.WithJSONOptions(opts...)}, nil,
		opts, []fuzzfill.Option{fuzzfill.WithNilContainers()})
}

// FuzzShapeAcceptsOmitZero pairs WithJSONOptions(OmitZeroStructFields)
// generation with the matching marshal option; the zero-heavy seed blobs
// exercise omission with the default fill.
func FuzzShapeAcceptsOmitZero(f *testing.F) {
	opts := []json.Options{json.OmitZeroStructFields(true)}
	fuzzShapeAcceptsOpts(f,
		[]jsonschema.GenerateOption{jsonschema.WithJSONOptions(opts...)}, nil, opts, nil)
}

// fuzzShapeAccepts is the shared body for every rig-2a target. Unlike rig 1 it
// generates and compiles inside the callback, since the type differs per
// iteration. The f.Fuzz callback cannot call t.Parallel (the fuzzing framework
// forbids it), the one documented exemption from the t.Parallel-everywhere
// convention.
//
// There is no WithNullable(false) target: reasonNullableOff.
func fuzzShapeAccepts(
	f *testing.F,
	genOpts []jsonschema.GenerateOption,
	validateOpts []jsonschema.ValidateOption,
) {
	f.Helper()
	fuzzShapeAcceptsOpts(f, genOpts, validateOpts, nil, nil)
}

// fuzzShapeAcceptsOpts is fuzzShapeAccepts with the marshal side configured
// in lockstep: an options-paired target (WithJSONOptions on the generation
// side) marshals its instances under the same encoding/json/v2 options, and
// may add fill draws the property needs (the nil-container target is
// toothless without nil containers). The refusal probe deliberately stays on
// default marshal options: generation's refusals are declaration-level and
// option-independent, while a shape-altering option can hide the faulty
// declaration from v2 before it is evaluated (OmitZeroStructFields omits a
// zero-valued field whose saturated fill is still zero -- an opaque type --
// so its invalid ,string tag never errs), which would break the agreement
// without any disagreement about the declaration.
func fuzzShapeAcceptsOpts(
	f *testing.F,
	genOpts []jsonschema.GenerateOption,
	validateOpts []jsonschema.ValidateOption,
	marshalOpts []json.Options,
	fillOpts []fuzzfill.Option,
) {
	f.Helper()

	ctx := context.Background()

	addShapeSeeds(f)

	f.Fuzz(func(t *testing.T, shape, values []byte) {
		rt := fuzzshape.Type(shape)
		schema, validator := generateAndCompile(ctx, t, rt, genOpts, validateOpts)
		instance := marshalShapeValue(t, rt, values, marshalOpts, fillOpts)

		err := validator.ValidateJSON(ctx, instance)
		if err != nil {
			t.Fatalf(
				"schema generated for a synthesized type rejected a value of that type\n"+
					"type:      %s\n"+
					"marshaled: %s\n"+
					"schema:    %s\n"+
					"error:     %v",
				rt, instance, indentSchema(t, schema), err,
			)
		}
	})
}

// FuzzShapeRejectsNearMiss asserts the generated schema is not vacuous. It runs
// on the default variant, where the object is closed, and builds two kinds of
// near miss from an instance the schema just accepted: an instance carrying one
// extra property, and an instance missing one required property.
//
// No draft or allOf gate is needed. AllOf composition fires only from
// needsAllOfComposition, which requires a registered TypeSchemaProvider, a
// WithTypeSchema override, or a JSONSchemaProvider; fuzzshape's pools are
// provider-free by construction, so no synthesized shape reaches it, and
// buildStructSchema therefore closes the object unless the shape carries a
// winning embedded fallback, whose extra-property leg the target skips
// (reasonFallbackAdmitsExtras). A StructOf root is inlined rather than
// extracted to $defs, so the root's Required list is readable directly.
func FuzzShapeRejectsNearMiss(f *testing.F) {
	ctx := context.Background()

	addShapeSeeds(f)

	f.Fuzz(func(t *testing.T, shape, values []byte) {
		rt := fuzzshape.Type(shape)
		schema, validator := generateAndCompile(ctx, t, rt, nil, nil)
		instance := marshalShapeValue(t, rt, values, nil, nil)

		// A StructOf root always marshals to an object, since the pools exclude
		// every embed that could promote a marshaler. Asserting it rather than
		// skipping keeps a pool change from turning the rig into a no-op.
		var object map[string]jsontext.Value

		require.NoErrorf(t, json.Unmarshal(instance, &object),
			"a value of %s marshaled to %s, which is not an object", rt, instance)

		// Unmarshaling null into a map succeeds and leaves it nil, so the error
		// check alone would let a null root reach the mutations below. Null is
		// exactly what a marshaler-promoting embed would produce.
		require.NotNilf(t, object, "a value of %s marshaled to null, not an object", rt)

		require.NotContainsf(t, object, nearMissSentinel,
			"the sentinel property is already present in %s, so injecting it is not a near miss", instance)

		if !shapeHasFallback(rt) {
			extra := maps.Clone(object)
			extra[nearMissSentinel] = jsontext.Value(`1`)
			requireRejects(ctx, t, validator, rt, schema, extra, "an unknown property")
		} else {
			t.Log(reasonFallbackAdmitsExtras)
		}

		for _, name := range schema.Required {
			require.Containsf(t, object, name,
				"schema generated for %s requires %q, which the marshaled instance %s does not carry",
				rt, name, instance)

			missing := maps.Clone(object)
			delete(missing, name)
			requireRejects(ctx, t, validator, rt, schema, missing, "a missing required property "+name)
		}
	})
}

// shapeHasFallback reports whether a drawn shape carries a winning embedded
// fallback. The pools draw fallbacks at depth 0 only (no embed pool type
// carries one), and a shape that drew two is a declaration refusal
// generateAndCompile already skipped, so a depth-0 scan for a non-anonymous
// ",embed" field of a qualifying type is exact.
func shapeHasFallback(rt reflect.Type) bool {
	for field := range rt.Fields() {
		if field.Anonymous || !strings.Contains(field.Tag.Get("json"), ",embed") {
			continue
		}

		ft := field.Type
		if ft.Kind() == reflect.Pointer && ft.Name() == "" {
			ft = ft.Elem()
		}

		if reflectkind.IsEmbeddedFallback(ft) {
			return true
		}
	}

	return false
}

// TestShapeFallbackNearMissTeeth pins reasonFallbackAdmitsExtras and restores
// the teeth the skip gives up: the fallback's value schema still judges every
// extra member, accepting one of the value type and rejecting one outside it.
func TestShapeFallbackNearMissTeeth(t *testing.T) {
	t.Parallel()

	ctx := t.Context()

	schema, err := jsonschema.GenerateFor[fbMap](ctx)
	require.NoError(t, err)

	validator, err := jsonschema.Compile(ctx, schema)
	require.NoError(t, err)

	require.NoError(t, validator.ValidateJSON(ctx, []byte(`{"name":"n","extra":7}`)),
		"an extra integer member satisfies the fallback's value schema")
	require.Error(t, validator.ValidateJSON(ctx, []byte(`{"name":"n","extra":"seven"}`)),
		reasonFallbackAdmitsExtras)
}

// requireRejects marshals a mutated object and fails unless the schema refuses
// it.
func requireRejects(
	ctx context.Context,
	t *testing.T,
	validator *jsonschema.Validator,
	rt reflect.Type,
	schema *jsonschema.Schema,
	object map[string]jsontext.Value,
	what string,
) {
	t.Helper()

	mutated, err := json.Marshal(object)
	require.NoErrorf(t, err, "marshal the near-miss instance for %s", rt)

	err = validator.ValidateJSON(ctx, mutated)
	if err == nil {
		t.Fatalf(
			"schema generated for a synthesized type accepted an instance carrying %s\n"+
				"type:      %s\n"+
				"near miss: %s\n"+
				"schema:    %s",
			what, rt, mutated, indentSchema(t, schema),
		)
	}
}

// generateAndCompile builds the schema for a synthesized type and compiles it,
// the step every rig-2 target opens with. Compiling runs the compile-time
// structure, identifier, and reference checks, so it doubles as the
// structural well-formedness assertion; full metaschema validation stays in
// conformance_test.go, too costly to run per iteration.
//
// A refused generation is not automatically a failure: the pools draw
// declarations encoding/json/v2 itself refuses (a tag with a cut name, a
// ",string" on a non-numeric field, an unnamed embedded non-struct, a struct
// with no serializable fields), and the ground-truth property then becomes
// agreement on the refusal. Generate may err only where v2 refuses to marshal the same type,
// asserted on a saturated fill so a nil pointer cannot hide the faulty
// declaration; the target then skips, having asserted the agreement.
func generateAndCompile(
	ctx context.Context,
	t *testing.T,
	rt reflect.Type,
	genOpts []jsonschema.GenerateOption,
	validateOpts []jsonschema.ValidateOption,
) (*jsonschema.Schema, *jsonschema.Validator) {
	t.Helper()

	schema, err := jsonschema.Generate(ctx, rt, genOpts...)
	if err != nil {
		requireV2RefusesValue(t, rt, err)
		t.Skipf("declaration refused by generation and encoding/json/v2 alike: %v", err)
	}

	validator, err := jsonschema.Compile(ctx, schema, validateOpts...)
	require.NoErrorf(t, err, "compile the schema generated for %s", rt)

	return schema, validator
}

// marshalShapeValue fills a value of rt from the value blob and marshals it. A
// marshal error is a failure rather than a skip, unlike rig 1's: fuzzshape's
// component pool is marshalable by construction and declares its own filling
// requirements through FillOptions, so a failure here means the pool or a
// constructor is wrong, not that the fuzzer found a hostile value.
func marshalShapeValue(
	t *testing.T, rt reflect.Type, values []byte,
	marshalOpts []json.Options, fillOpts []fuzzfill.Option,
) []byte {
	t.Helper()

	val := reflect.New(rt)
	fuzzfill.Fill(val, values, append(fuzzshape.FillOptions(), fillOpts...)...)

	instance, err := json.Marshal(val.Interface(), marshalOpts...)
	require.NoErrorf(t, err, "marshal a value of %s", rt)

	return instance
}

// requireV2RefusesValue asserts encoding/json/v2 also refuses to marshal a
// value of rt, the agreement a refused generation pins. The fill is saturated
// so a nil pointer cannot hide the faulty declaration behind a null.
func requireV2RefusesValue(tb testing.TB, rt reflect.Type, genErr error) {
	tb.Helper()

	val := reflect.New(rt)
	fuzzfill.Fill(val, bytes.Repeat([]byte{0xff}, 512), fuzzshape.FillOptions()...)

	_, err := json.Marshal(val.Interface())
	require.Errorf(tb, err,
		"generation refused %s (%v) but encoding/json/v2 marshals it", rt, genErr)
}

// indentSchema renders a schema for a failure message. It runs only on the
// failure path, since the schema differs per iteration and rendering every one
// would cost more than the property check itself.
func indentSchema(tb testing.TB, schema *jsonschema.Schema) []byte {
	tb.Helper()

	rendered, err := json.Marshal(schema, jsontext.WithIndent("  "))
	require.NoError(tb, err, "marshal the generated schema for the failure message")

	return rendered
}

// shapeSeedDraws indexes the shape blobs the seed corpus draws from
// [fuzzshape.Blobs]. The seeds are the only part of rig 2 the fast gate runs,
// so they are chosen rather than arbitrary: the byte patterns one reaches for
// by hand -- all zeros, all ones, a repeating nibble -- drive every draw to the
// same residue, which collapses the shape to at most one field once the name
// dedupe runs. TestShapeSeedsDrawRichShapes states what the set has to cover.
var shapeSeedDraws = []int{79, 85, 162, 372, 1976}

// seedShapeBlobs returns the population shapeSeedDraws indexes into.
func seedShapeBlobs() [][]byte {
	return fuzzshape.Blobs(slices.Max(shapeSeedDraws) + 1)
}

// addShapeSeeds seeds a rig-2 target. It pairs each shape blob with a value
// blob alternating the two ends of the value axis: zeroed leaves every pointer
// nil, saturated sets them.
func addShapeSeeds(f *testing.F) {
	f.Helper()

	// The field-free struct, whose schema closes an object with no properties.
	f.Add([]byte{}, []byte{})

	blobs := seedShapeBlobs()
	for i, draw := range shapeSeedDraws {
		values := bytes.Repeat([]byte{0xff}, 96)
		if i%2 == 0 {
			values = make([]byte, 96)
		}

		f.Add(blobs[draw], values)
	}
}

// TestShapeSeedsDrawRichShapes asserts the seed corpus is worth running. A
// corpus drawing only thin shapes would leave every target passing while
// covering nothing, and silently, since a thin shape is still a valid one.
// Asserting properties of the draws makes that loud, and the Required check is
// what gives FuzzShapeRejectsNearMiss's Required loop a body on the gate.
//
// The two embed classes are the ones a synthesized rig is best placed to fuzz
// and the reason the set is this size: encoding/json drops a name two embeds
// promote at equal depth, and lets an outer field shadow a deeper one. Both are
// read off the embedded type's own generated schema rather than re-derived
// here, so the guard cannot disagree with the resolution rules under test.
//
// The indices are positions in a generated population, so any change to the
// pools or the draw odds re-rolls what they name; this guard is what forces
// them to be re-chosen instead of quietly going thin.
func TestShapeSeedsDrawRichShapes(t *testing.T) {
	t.Parallel()

	ctx := t.Context()
	blobs := seedShapeBlobs()

	fieldClasses := map[string]func(reflect.StructField) bool{
		"an embedded field": func(f reflect.StructField) bool {
			return f.Anonymous
		},
		"an unexported field": func(f reflect.StructField) bool {
			return !f.IsExported()
		},
		"a ,string coercion": func(f reflect.StructField) bool {
			return strings.Contains(f.Tag.Get("json"), ",string")
		},
		"a tag naming a property": func(f reflect.StructField) bool {
			name, _, _ := strings.Cut(f.Tag.Get("json"), ",")

			return name != "" && name != "-"
		},
		"an embedded fallback": func(f reflect.StructField) bool {
			return !f.Anonymous && strings.Contains(f.Tag.Get("json"), ",embed")
		},
		"a format tag option": func(f reflect.StructField) bool {
			return strings.Contains(f.Tag.Get("json"), ",format:")
		},
	}

	seen := make(map[string]bool, len(fieldClasses)+2)

	for _, draw := range shapeSeedDraws {
		rt := fuzzshape.Type(blobs[draw])
		require.GreaterOrEqualf(t, rt.NumField(), 3, "seed draw %d yields the thin shape %s", draw, rt)

		schema, err := jsonschema.Generate(ctx, rt)
		if err != nil {
			// A refused draw earns its seed slot only through the refusal
			// half of the property, v2 refusing the same declaration. The
			// format-option class is reachable no other way.
			requireV2RefusesValue(t, rt, err)
		} else {
			require.NotEmptyf(t, schema.Required, "seed draw %d (%s) requires no property", draw, rt)
			markPromotionClasses(ctx, t, rt, schema, seen)
		}

		for field := range rt.Fields() {
			for name, match := range fieldClasses {
				if match(field) {
					seen[name] = true
				}
			}
		}
	}

	for name := range fieldClasses {
		require.Truef(t, seen[name], "no seed draw carries %s", name)
	}

	require.True(t, seen[droppedClass], "no seed draw drops a name two embeds promote at equal depth")
	require.True(t, seen[shadowedClass], "no seed draw shadows a promoted name with an outer field")
}

// Names of the two embed-resolution classes markPromotionClasses records.
const (
	droppedClass  = "a promoted name dropped at equal depth"
	shadowedClass = "a promoted name shadowed by an outer field"
)

// markPromotionClasses records which embed-resolution rules a drawn shape
// exercises, by comparing each untagged struct embed's own generated schema
// against the root's: a promoted property missing from the root was dropped,
// and one carrying a different type was shadowed by an outer field.
func markPromotionClasses(
	ctx context.Context,
	t *testing.T,
	rt reflect.Type,
	schema *jsonschema.Schema,
	seen map[string]bool,
) {
	t.Helper()

	for field := range rt.Fields() {
		// A name part is what suppresses promotion, so an options-only tag on an
		// embed still promotes and must be inspected.
		tagName, _, _ := strings.Cut(field.Tag.Get("json"), ",")
		if !field.Anonymous || tagName != "" {
			continue
		}

		embedded := field.Type
		if embedded.Kind() == reflect.Pointer {
			embedded = embedded.Elem()
		}

		if embedded.Kind() != reflect.Struct {
			continue
		}

		promoted, err := jsonschema.Generate(ctx, embedded)
		require.NoErrorf(t, err, "generate a schema for the embedded %s", embedded)

		for name, sub := range promoted.Properties {
			at, ok := schema.Properties[name]
			switch {
			case !ok:
				seen[droppedClass] = true
			case at.Type != sub.Type:
				seen[shadowedClass] = true
			}
		}
	}
}
