// Package keyword holds the canonical JSON Schema keyword-name constants. The
// jsonschema package re-exports them as its public Keyword* constants, and
// internal consumers (such as the struct-tag parser) reference them directly, so
// the names live here as a single source of truth and can be shared without an
// import cycle through the main package.
package keyword

// JSON Schema keyword names.
const (
	AdditionalItems       = "additionalItems"
	AdditionalProperties  = "additionalProperties"
	AllOf                 = "allOf"
	AnyOf                 = "anyOf"
	Const                 = "const"
	Contains              = "contains"
	ContentEncoding       = "contentEncoding"
	ContentMediaType      = "contentMediaType"
	ContentSchema         = "contentSchema"
	Default               = "default"
	Definitions           = "definitions"
	Defs                  = "$defs"
	Dependencies          = "dependencies"
	DependentRequired     = "dependentRequired"
	DependentSchemas      = "dependentSchemas"
	Deprecated            = "deprecated"
	Description           = "description"
	DynamicRef            = "$dynamicRef"
	Else                  = "else"
	Enum                  = "enum"
	Examples              = "examples"
	ExclusiveMaximum      = "exclusiveMaximum"
	ExclusiveMinimum      = "exclusiveMinimum"
	Format                = "format"
	If                    = "if"
	Items                 = "items"
	MaxContains           = "maxContains"
	Maximum               = "maximum"
	MaxItems              = "maxItems"
	MaxLength             = "maxLength"
	MaxProperties         = "maxProperties"
	MinContains           = "minContains"
	Minimum               = "minimum"
	MinItems              = "minItems"
	MinLength             = "minLength"
	MinProperties         = "minProperties"
	MultipleOf            = "multipleOf"
	Not                   = "not"
	OneOf                 = "oneOf"
	Pattern               = "pattern"
	PatternProperties     = "patternProperties"
	PrefixItems           = "prefixItems"
	Properties            = "properties"
	PropertyNames         = "propertyNames"
	ReadOnly              = "readOnly"
	Ref                   = "$ref"
	Required              = "required"
	Then                  = "then"
	Title                 = "title"
	Type                  = "type"
	UnevaluatedItems      = "unevaluatedItems"
	UnevaluatedProperties = "unevaluatedProperties"
	UniqueItems           = "uniqueItems"
	WriteOnly             = "writeOnly"
)
