version: "3"

set: [errexit, nounset, pipefail]
shopt: [globstar]

tasks:
  hooks:install:
    desc: Installs git hooks
    preconditions:
      - sh: command -v lefthook
        msg: "lefthook is not installed. Run 'task install' first."
    cmds:
      - lefthook install
